<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<div class="product alert <?= $block->getHtmlClass() ?>">

    <form name="stock-notification" id="stock-notification" action="" method="post">

         <label for="email">Email</label>
         <input id="email" name="email" class="input-text required-entry" />

    </form>


        <a href="#" data-post='<?= /* @noEscape */ $block->getPostAction() ?>'
           title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
            <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
        </a>


    <p>loaded ffrom theme file</p>
</div>
